### PR TITLE
Add Study Session feature

### PR DESCRIPTION
**Pull request by fabien-renaud**
## Create a study session
  - **Command:** `!study`
  - **Parameters:**
    - **author:** The author of the message (Discord API)
    - **date:** Automatically detect `YYYY/MM/DD` `YYYY-MM-DD` format
    - **Time:** Automatically detect `HH:mm` `HH:mm am` `HH:mm pm` format(case insensitive)
    - **estimatedLength:** Automatically detect `x hour` `xx min` format (case insensitive, allow variations such as `\dhours`)
  - Cases:
    - **Success:** Every parameter has been detected, the study session is registered
    - **Error:** An error occurs while creating the session. The session is cancelled
    - **`date` is missing:** `date` is missing or hasn't been detected. The user is proposed to try again
    - **`date` is past:** `date` is past. The user is proposed to try again
    - **`estimatedLength` is missing:** `estimatedLength` is missing or hasn't been detected. The user is proposed to try again
  - Preview:
    image

## Fetch upcoming study sessions
  - **Command:** `!next study`
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The sessions are displayed
    - **Not found:** There's no session to display
    - **Error:** An error occurs while subscribing to the session. The user is proposed to try again
  - Preview: 
    image

## Subscribe to a study session
  - **Command:** React with a ⭐ to a `!study` message
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The user is subscribed to the session. He will receive a DM one hour before the session starts
    - **Error:** An error occurs while subscribing to the session. The user is proposed to try again
  - Preview: 
    image
    image
    Notification:
      image

## Unsubscribe to a study session
  - **Command:** Remove the ⭐ reaction to a `!study` message
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The user is unsubscribed to the session
    - **Error:** An error occurs while subscribing to the session. The user is proposed to try again
  - Preview:
    image
    image

## Cancel a study session
  - **Command:** React with a ❌ to a `!study` message. Only author and moderators can do that
  - **Validation:** This command requires a validation to prevent mishandling
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The study session is deleted
    - **Cancel:** The study sessions hasn't been validated. No cancellation occurs
    - **Time elapsed:** The user didn't answer second validation. No cancellation occurs
    - **Unauthorized:** The user attempting to cancel the session isn't the session owner. No cancellation occurs
    - **Error:** An error occurs while deleting the session. The user is proposed to try again
  - Preview:
    image
    - Confirm cancel:
      image
      image
    - Cancel cancel:
      image
    - Time elapsed:
      image

### CODE REVIEW

**Comment by fabien-renaud** [comment]
Hey @crobin93 @Fox-Islam,

The development should be finished in the coming days, here's the list of use cases that I can already list:

## Create a study session
  - **Command:** `!study`
  - **Parameters:**
    - **author:** The author of the message (Discord API)
    - **date:** Automatically detect `YYYY/MM/DD` `YYYY-MM-DD` format
    - **Time:** Automatically detect `HH:mm` `HH:mm am` `HH:mm pm` `format(case insensitive)
    - **estimatedLength:** Automatically detect `x hour` `xx min` format (case insensitive, allow variations such as `\dhours`)
  - Cases:
    - **Success:** Every parameter has been detected, the study session is registered
    - **Error:** An error occurs while creating the session. The session is cancelled
    - **`date` is missing:** `date` is missing or hasn't been detected. The user is proposed to try again
    - **`date` is past:** `date` is past. The user is proposed to try again
    - **`estimatedLength` is missing:** `estimatedLength` is missing or hasn't been detected. The user is proposed to try again

## Subscribe to a study session
  - **Command:** React with a ⭐ to a `!study` message
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The user is subscribed to the session. He will receive a DM one hour before the session starts
    - **Error:** An error occurs while subscribing to the session. The user is proposed to try again

## Unsubscribe to a study session
  - **Command:** Remove the ⭐ reaction to a `!study` message
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The user is unsubscribed to the session
    - **Error:** An error occurs while subscribing to the session. The user is proposed to try again

## Cancel a study session
  - **Command:** React with a ❌ to a `!study` message. Only author and moderators can do that
  - **Parameters:** Everything is automatically detected by Discord API
  - Cases:
    - **Success:** The study session is deleted
    - **Error:** An error occurs while deleting the session. The user is proposed to try again

**Comment by fabien-renaud** [comment]
Since the new feature is almost functional (more than sending a private message one hour before the beginning), I let myself try some nice designs with Discord Message API! 
I'm planning to move the reaction buttons to the bot's message, so it'll be clearer.
I also plan to add the user's original message into the embed message, and put the instructions messages in italic.

Feedbacks and suggestions are appreciated :D

**Old version:**
image

**New version:**
image

**Comment by fabien-renaud** [comment]
I've setted up cache loading for messageReactions, that means now you can read messageReactions from messages that have been sent before the server start.

**Comment by fabien-renaud** [comment]
> I've setted up cache loading for messageReactions, that means now you can read messageReactions from messages that have been sent before the server start.

**Comment by fabien-renaud** [comment]
The feature is ready to review, here's the common cases:
Create

**Comment by chris-mcdonald-dev** [comment]
✨ This looks absolutely amazing! I love it.✨ 

I've been going through the existing code structure to work with strict mode.
Since there were a few errors being thrown by some of the functions in `games.js`, I did some basic refactoring like we discussed.

I was initially confused about why my date wasn't being accepted. So I also added some clarity to the error messages sent to users regarding the accepted date and time formats.

image


I fixed a small typo in the `fullHour` variable declaration of `getUTCFullTime()`. The condition was still appending 0 on the front of the hour for 10:00.

image

I'm considering implementing a testing framework like Jest to help us keep everything functional for future features and tasks. If you have any suggestions, let me know!

(Also, I agree with you about the prettier thing. Lol)

**Comment by fabien-renaud** [comment]
Thanks for your enthousiasm!

I made a little fix so we can use either 1 or 2 digit number for defining `startDate ` hour (it doesn't impact `Date` creator) :

image

I've already set up ESLint and Prettier on another feature branch (not pushed yet), we will talk about that and testing stuff later :)

**Comment by chris-mcdonald-dev** [comment]
Okay everything looks good!

There are just a few things we can consider for future updates:

- It would be nice to have a way for moderators to remove upcoming study sessions even if they are not the one who registered it without having to go into the DB. *(Perhaps there is a way and I'm just not aware if it yet though!)*

- I noticed in `notifySubscribers.js` you have it written that subscribers will notified one hour before the beginning of the session. I tried this initially and it seemed to work, but after our past few commits, I couldn't get it to work anymore. Do you mind walking me through what's happening in that function over Discord?

**Pull request merged**
