### PR TITLE
Fix repeated randomized word by shuffling once per game

### PR DESCRIPTION
**Pull request by briwa-angelswing**
I noticed that when playing the game today, there's a chance that the word repeats in between rounds.

screenshot_514

Not sure if this is an intended behavior, but I think it would be great if the words are completely random, or at least that's what I expected :sweat_smile: 

The changes would also reduce the calls to Google Sheets (from `GoogleSheets.fetchVocab`) from doing it each round to just once per game, i.e. by creating the list of shuffled words for the amount of rounds once in the beginning.

Let me know if this is OK! Also, I don't think this needs to wait for #57 since the changes are not related to discord API in particular. Thank you!!

### CODE REVIEW

**Comment by Fox-Islam** [comment]
Hey @briwa-angelswing, thanks for this PR! I didn't expect the rest of this comment to be so long, sorry in advance!

I haven't had a chance to check the branch out and try it for myself yet but from the code I think there'll be a couple of issues showing up
- Because the check is looking for if the shuffled words is `undefined`, and then initialising it and popping values off each time, once the list is exhausted the shuffled words will no longer be `undefined`, instead it'll be `[]` so the words won't be reinitialised based on the check
- If the number of words in the vocab list isn't a multiple of the number of rounds, when it tries to select words there'll be some potentially weird behaviour if the list of words is empty and there are still rounds left (For example, if the list contains 23 words, the first four games after initialisation will be fine but the fifth one will only have 3 words to select from for the whole five rounds?)
- The shuffled words are initialised _after_ the vocab list is selected (review vocab or the vocab for the current week) so each game will be tied to one list until the list is reinitialised (after which the next few games will be tied to that list until reinitialisation, and so on)

I think the first two can be solved by changing 
```javascript
if (global.typingGame.shuffledWords === undefined) {
```
to something more like
```javascript
if (!global.typingGame.shuffledWords || global.typingGame.shuffledWords.length < NUM_OF_ROUNDS) {
```

If you want to keep the shuffled words system I think the last issue might be solved by fetching both lists, combining them into one list and then making the shuffled words list from that - though in that case, we'll also lose the 25% probability thing where we have a preference for current vocab. Could get around this by throwing that current vocab list into the shuffled words list two extra times (so that it contains 3 instances of the current vocab and one of the previous) to change the percentages a little, but then we're back to where we were prior to this PR where words will have a chance to be repeated 😅 

The actual fix for that I think would, instead, be not creating a shuffled words list at all, fetch both lists and do the weighted random index search per round, but remove the item from its respective vocab list as soon as it's selected. This way a word has less chance of being reselected in a single game. As soon as a list is empty, make another fetch and refill the list.

Sorry again for the length of this comment! I think the benefit of not doing frequent calls to Google Sheets is valuable. Similar work was done (but to a much lesser extent) in #51 to cut down from five calls to the API per game to two calls per game. Moving to one or two calls every _few_ games like here would be better, I think.

**Comment by chris-mcdonald-dev** [comment]
Thanks so much for helping out!

In addition to what fox shared --

Although this may not have been initially considered, one benefit to having the vocab words potentially repeat across different rounds comes from one of the main objectives of the exercise being to increase familiarity with the new weekly vocabs.

Is a removal of that repetition the direction we'd like to go with this? Certainly open to ideas!

**Comment by briwa-angelswing** [comment]
Hello, thanks for the response @Fox-Islam and @chris-mcdonald-dev !! I think it was a detailed long response so I really appreciated that.

> Because the check is looking for if the shuffled words is undefined, and then initialising it and popping values off each time, once the list is exhausted the shuffled words will no longer be undefined, instead it'll be [] so the words won't be reinitialised based on the check

I'm not sure if this is going to be the case, because after [a game ends](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L143-L154), `global.typingGame` is [cleared out](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L177) with `{}`, so the next time `typingGame` is called, `global.typingGame.shuffledWords` is going to be undefined... right? Or maybe I missed something? :sweat_smile: 

> If the number of words in the vocab list isn't a multiple of the number of rounds, when it tries to select words there'll be some potentially weird behaviour if the list of words is empty and there are still rounds left (For example, **if the list contains 23 words, the first four games after initialisation will be fine but the fifth one will only have 3 words to select from for the whole five rounds?**)

I'm not sure if I understand this comment fully. Were you talking about this part of the code where [`vocabList` is spliced](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L93)?
In my understanding, `vocabList` is always going to be [a new array fetched from the Google Sheets every time the game starts](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L80) (unless I'm mistaken... CMIIW!). So if the `vocabList` has 23 words, 5 will only be taken from it each game. The next time the code gets the shuffled words, it'll be 23 words again. But please you can elaborate more on your comment, or maybe next time you can comment on the specific part of the code itself so I know more of the context :smile: 

> The shuffled words are initialised after the vocab list is selected (review vocab or the vocab for the current week) so each game will be tied to one list until the list is reinitialised (after which the next few games will be tied to that list until reinitialisation, and so on)

I assume you were talking about [this part of the code](https://github.com/chris-mcdonald-dev/korean-discord-app/pull/58/files#diff-4bddad59088befbd69c0c25ce73de7cb09f405f7a0246dda8d0709633a76e994R79), right? So in my opinion, it'd make more sense if each game of 5 rounds is somewhat tied to a consistent list, as opposed to the previous code where it wants to be randomly selected to either list. In other typing games, you'd typically choose a category for each round, probably so that it's easier to play with one context in a game and also to improve that specific context of the vocab. But again, seems like this is a requirement I wasn't aware of, so I'm happy to comply either way.

>  one benefit to having the vocab words potentially repeat across different rounds comes from one of the main objectives of the exercise being to increase familiarity with the new weekly vocabs.
> 
> Is a removal of that repetition the direction we'd like to go with this?

My only issue with this is that even if repeating the words was the direction to go for, with the current code, there's a chance that randomness will pick the same word for the entire 5 rounds if you're lucky (or unlucky? :joy:), which IMO defeats the purpose in picking a random word. When I noticed the repeating words, I thought it was an unwanted flaw in the code (it reminded me of [one of my favorite articles](https://blog.codinghorror.com/the-danger-of-naivete/), check it out if you haven't heard about this, really good!), so I tried to fix it.

My opinion is to keep it random at least in a game of 5 rounds, so that the premise is actually "give 5 random words from the list and practice typing it" instead of "give 5 words that might be random". The list might repeat for the next one, but at that point, it's the user who decided to repeat, not the code. But of course, this was more of a UX question then, and there are many ways to do it, so I'm also open for ideas.

---
Regarding the rest of the comments (weighted random words), I'm not entirely sure if we wanted to go that far :sweat_smile: I'm a fan of making small changes and test it out, if it comes to finding out what works for the users or what people prefer.

Also I saw the work of #51 and I do think that I should wait for that one to get merged first, since it seems like the flow of the code is quite heavily rewritten... so I think I'll close this PR for now.

Thank you for the discussion!! Really appreciated. I'm not heavily involved in the study group nor this codebase, so my interpretation of the code and the game are currently lacking, so please correct me if I'm wrong. Cheers!

**Comment by briwa-angelswing** [comment]
Closing this PR in favor of getting #51 to get merged first, then I'll see what I can do :eyes:

**Comment by Fox-Islam** [comment]
> I'm not sure if this is going to be the case, because after [a game ends](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L143-L154), `global.typingGame` is [cleared out](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L177) with `{}`, so the next time `typingGame` is called, `global.typingGame.shuffledWords` is going to be undefined... right? Or maybe I missed something? 😅

You're totally right! Yeah, if the end of the game is reached it should be cleared out and match the `if` every time the game starts

> I'm not sure if I understand this comment fully. Were you talking about this part of the code where [`vocabList` is spliced](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L93)?
> In my understanding, `vocabList` is always going to be [a new array fetched from the Google Sheets every time the game starts](https://github.com/chris-mcdonald-dev/korean-discord-app/blob/ce1becc6a5c3e969a4d4271fe9a9e7c702364c71/src/scripts/activities/games.js#L80) (unless I'm mistaken... CMIIW!). So if the `vocabList` has 23 words, 5 will only be taken from it each game. The next time the code gets the shuffled words, it'll be 23 words again. But please you can elaborate more on your comment, or maybe next time you can comment on the specific part of the code itself so I know more of the context 😄

Yep! This point was dependant on the typing game not being reset, but if it is then the list should be refetched each time as you say

> Also I saw the work of #51 and I do think that I should wait for that one to get merged first, since it seems like the flow of the code is quite heavily rewritten... so I think I'll close this PR for now.

Sure thing! I think the biggest driving force for that PR was to move away from global variables since they were adding a little bit more effort and confusion in managing state, hopefully the changes there make future changes like this PR easier to implement

**Pull request closed without merging**
