### PR TITLE
Add new translation exercise

### PR DESCRIPTION
**Pull request by Fox-Islam**
- Added new exercise to games.js where the goal is to translate a term into Korean
- Moved the word lists out into a separate file (dictionary.js)
- Updated the game explanation message to include the additional exercise

### CODE REVIEW

**Comment by Fox-Islam** [comment]
The main change that I wanted to do but thought it would be a bit too much to do in this PR was to make some of the shared code between the two games more generalised

Some of the code in the game functions use `global.typingGameImportantValue` and I pretty much just copied it and made the translating game use `global.translatingGameImportantValue` 
I was thinking that instead we could do something like have a global variable called `global.currentGame` which would be a string like `global.currentGame = "translatingGame"` and then when we need one of the specific variables we could access it from `global` by doing `global[global.currentGame + "ImportantValue"]` which would parse as `global["translatingGameImportantValue"]` and act the same as `global.translatingGameImportantValue` (hopefully)

I'm not sure how much of the shared code could be refactored like that or if it would end up making it harder to understand,  though, so would like to know what you think before diving in and trying it out

**Comment by Fox-Islam** [comment]
Another change was one that I partially did in the games.js file where I added the `isExercisesChannel()` and `isTestChannel()` - I was thinking of, instead of having those functions in games.js, adding another file called channel-helpers.js or something which exports those as well as `isKoreanChannel()`, `isLinksChannel()` etc so that they can be used anywhere else that checks those things (I think it's only index.js and games.js right now)

**Comment by Fox-Islam** [comment]
Concept I want to float that I don't think is possible right now with how the game works:
After giving an incorrect answer (for instance '들어오다' for "To go in") the bot responds with something like "Close! The actual answer was '들어**가**다'" by doing some sort of `string.split()` and comparing each character. 
I checked in the ultimate Javascript development environment (Google Chrome's F12 console) and doing a `.length` on 들어가다 _does_ return 4 so I think it would be possible code-wise
Buuuuuut it looks like the games don't currently have a failure state (other than timeout), if someone gets a question wrong they can keep trying - which I think is fine but means that in this version of the translation game if you never get the correct answer you might never find out what the translation is

**Comment by chris-mcdonald-dev** [comment]
> The main change that I wanted to do....

I definitely think this would functionally behave the same way!

I think I may need help understanding how this could potentially improve the experience or scalability. I can imagine if exercises added in the future were to behave similarly to these this would make copying-pasting a template to start coding from easier. I'm not sure how many exercises will behave as similarly as these two though.

But I feel like I might be missing something, so I'd like to hear your thoughts!

**Comment by chris-mcdonald-dev** [comment]
> Another change was one that I partially did in the games.js....

I saw the change you made and love it! I think utilities.js might be a good place for those.

> Concept I want to float that I don't think is possible right now....

Thinking about it now, I absolutely think that's possible. :sparkles: I think we'll need to remember run a `.filter(Boolean)` as well to avoid nulls. While working on the expletive filter I noticed that working with Korean characters tends to spit out a lot of nulls when `.split()` is run on them.

> ....if someone gets a question wrong they can keep trying....

Right, my idea behind the exercises was to set them up in a way that was collaborative so multiple users could participate at once. :smiley: So I think a simple correction message would work well!

`Edit:` I also think checking if the answers users send are in Korean and then either sending a correction message ***or*** a message pointing them to the vocab words in the `#weekly-vocabulary` channel if they are just typing an entirely different message might be good!

**Comment by Fox-Islam** [comment]
> I definitely think this would functionally behave the same way!
> 
> I think I may need help understanding how this could potentially improve the experience or scalability. I can imagine if exercises added in the future were to behave similarly to these this would make copying-pasting a template to start coding from easier. I'm not sure how many exercises will behave as similarly as these two though.
> 
> But I feel like I might be missing something, so I'd like to hear your thoughts!

The current setup requires each exercise to have three functions coded for it: `game`, `gameListener` and `endGame`
The game function has the core logic of the game so I think that'll end up being quite different for anything added in the future but I'm hoping that enough of `gameListener` and `endGame` are common between each game that we could move towards a system where we only have one initialisation and one teardown function that can manage them all. 

If It can be done, I think the benefits would be:
- For new exercises, only a game function would need to be written to handle the gameplay 
- The game itself wouldn't need to know about how it was created or how to destroy itself, a person contributing a game only interacts with variables that are important to the gameplay without worrying about how to correctly maintain the state of unrelated flags

My main concern is that, with the size and relative simplicity of games.js, a change like this will probably end up making the code more difficult to follow _right now_ even if it there's a possibility that it may make it easier to maintain in the future

> I saw the change you made and love it! I think utilities.js might be a good place for those.

Ahh, cool! Would you prefer that change to be included in this branch (to complete the partial change) or as a separate stand-alone task?

> Thinking about it now, I absolutely think that's possible. ✨ I think we'll need to remember run a `.filter(Boolean)` as well to avoid nulls. While working on the expletive filter I noticed that working with Korean characters tends to spit out a lot of nulls when `.split()` is run on them.
>
> Right, my idea behind the exercises was to set them up in a way that was collaborative so multiple users could participate at once. 😃 So I think a simple correction message would work well!
> 
> `Edit:` I also think checking if the answers users send are in Korean and then either sending a correction message _**or**_ a message pointing them to the vocab words in the `#weekly-vocabulary` channel if they are just typing an entirely different message might be good!

That's a good shout, will probably also have to remember to do some other sanitisation just to make sure we don't end up accidentally doing `.split()` on an image or something and having the bot error out 😅

**Comment by Fox-Islam** [comment]
Just to keep track, before opening up this PR as ready to review I still need to 
- [x] Test the new feature to make sure it works at all
- [x] Test previous features to make sure they still work
- [x] Maybe change the gameplay messages for the current feature to make sure they make sense
- [ ] ~~Rename the game to... Something better??~~ Searching for a perfect name is a fool's errand
- [x] Update README command table

**Comment by Fox-Islam** [comment]
Amended the commit to address two things that I think were bugs, one in expletives.js and one in index.js, here's the amendment:
https://github.com/crobin93/korean-discord-app/compare/a3979a10c4886c9db35aaf37b538fde83cce597e..89175c2bc4b44b67ba57f823742f87b4aef888e5

Unrelated discussion to this branch entirely:
The `endsWith` fix works for now but I'm not sure what the plans are for `!xyz` commands in general - if it's expected that more will be introduced then I think a `getCommand()` function that does something like 
```javascript
function getCommand(message) {
    match = \\![a-z]+\.exec(message); // https://regexr.com/5k0cu
    if (match === null) {
        return null;
    }
    return match[0];
}
```
(or the equivalent without regex) might be a bit more flexible (For instance if there's ever a command that might require some sort of additional input after the command like "!t \<number of rounds\>")

**Comment by chris-mcdonald-dev** [comment]
I fetched your branch and tried out your new changes, and as a stand-alone game, they work great! This is awesome.

There are just a few things I noticed that are going to be a small challenge for us.
- Firstly, I'm realizing when users use the command `!t` to start the exercise while it's already in progress, the teardown function wasn't terminating correctly. The `listenerFlag` was initially in the wrong place and there was a mistake in the `if` statement's condition in the initiating function. I'll be fixing that in the main branch as well.
- Secondly, because there are many times when users ***don't*** complete the exercise, I'm just anticipating there will times when people **switch to another exercise while another is in progress**. Currently, the teardown function is not shared between exercises, and so exercises don't work too well together at the moment.

>> The current setup requires each exercise to have three functions coded for it: game, gameListener and endGame [...] I'm hoping that enough of gameListener and endGame are common between each game that we could move towards a system where we only have one initialisation and one teardown function that can manage them all.

Ah okay, yes this makes a lot of sense. I'm thinking there might be some variation between the explanation messages and we could just have those as separate functions that we call based on which game is running.
As far as the shared functions, perhaps we could make an array with all of the names of the exercises and run a `.forEach()` method using that parsing approach you suggested within one single teardown function. I'm now understanding that would: 
- Allow them to all share the same `endGames()` function as you cleverly mentioned.
- And also allow us to run that shared teardown function whenever a user switched exercises mid-game, hopefully fixing our compatibility issue.

I'm realizing is these games are all going to have to share a common `listenerFlag` as opposed to the separate setup we have now.

>>Ahh, cool! Would you prefer that change to be included in this branch (to complete the partial change) or as a separate stand-alone task?

For the initial creation, it's pretty much only used by games.js right now, so I think it'll be fine to include it in this branch! What do you think?

>> That's a good shout, will probably also have to remember to do some other sanitisation just to make sure we don't end up accidentally doing .split() on an image or something and having the bot error out 😅

😂 That's actually something I didn't anticipate at all. But I've been running `.split()` on messages this entire time with the expletive filter and didn't even stop to think twice about it. Luckily, I think Discord gives messages a separate `.attachments` property specifically for images/videos, so we shouldn't have to worry about that. 🤞

**Comment by chris-mcdonald-dev** [comment]
I also made some changes to make sure the message listeners didn't take precedence over the actual commands to start the new exercise in `index.js`.

**Comment by Fox-Islam** [comment]
> * Secondly, because there are many times when users _**don't**_ complete the exercise, I'm just anticipating there will times when people **switch to another exercise while another is in progress**. Currently, the teardown function is not shared between exercises, and so exercises don't work too well together at the moment.

A possible workaround for this right now is to make the switch statement handle a bit more of the logic:
```javascript
switch (true) {
    // Start Typing Game
    case (text.includes(process.env.CLIENT_ID) && (text.includes("typing")) || text.endsWith("!t")):
        if (global.translatingFlag === true) {
            endTranslatingGame(message, false); 
        }
        typingGame(message, client);
        break;
    // Pass Message to Listener (while exercise is in progress)
    case global.typingFlag === true:
        typingGameListener(message, client);
        break;
    // Start Translating Game
    case (text.includes(process.env.CLIENT_ID) && (text.includes("translating")) || text.endsWith("!tr")):
        if (global.typingFlag === true) {
            endTypingGame(message, false);
        }
        translatingGame(message, client);
        break;
    // Pass Message to Listener (while exercise is in progress)
    case global.translatingFlag === true:
        translatingGameListener(message, client);
        break;
    // Stop any running game
    case text.includes(process.env.CLIENT_ID) && text.includes("stop"):
        if (global.translatingFlag === true) {
            endTranslatingGame(message, true); 
        }
        if (global.typingFlag === true) {
            endTypingGame(message, true);
        }
        break;
}
```
Here, the 'stop' command should terminate any/all running games, and the start commands each end any other running games but this will definitely get more and more difficult to maintain for each additional command, it's already looking kind of daunting 😅 

> Ah okay, yes this makes a lot of sense. I'm thinking there might be some variation between the explanation messages and we could just have those as separate functions that we call based on which game is running.
> As far as the shared functions, perhaps we could make an array with all of the names of the exercises and run a `.forEach()` method using that parsing approach you suggested within one single teardown function. I'm now understanding that would:
> 
> * Allow them to all share the same `endGames()` function as you cleverly mentioned.
> * And also allow us to run that shared teardown function whenever a user switched exercises mid-game, hopefully fixing our compatibility issue.
> 
> I'm realizing is these games are all going to have to share a common `listenerFlag` as opposed to the separate setup we have now.

That sounds right, I think it's probably worth opening up a PR branched off this one to make a small attempt at this and we can iron out the specifics of the refactor in that branch, I'll keep this a draft until we're either happy with how that's going or realise that it's making things worse due to unforeseen issues 😅

**Comment by Fox-Islam** [comment]
Here's a branch with a first pass at the refactor, it's a bit awful to read in GitHub's diff but hopefully it's not too bad in VS Code: https://github.com/Fox-Islam/korean-discord-app/pull/1
Unfortunately it had to go into the forked repo because this branch doesn't exist in this repository for... **git** reasons 😅

**Comment by Fox-Islam** [comment]
Closing this since it'll be much easier to just redo it after #51 is merged rather than trying to rebase this

**Pull request closed without merging**
